# Site Settings
title: Choiflix HyungIn's World
email: mikail0205@gmail.com
description: Univ. student of Kyungpook National Univ. Majoring Computer Science and Enigneering. Using this git page for documenting my personal study.
baseurl: 
# the subpath of your site, e.g. /blog
url: "mikail0205.github.io"
# the base hostname & protocol for your site
google_analytics: 

# User Settings
username: HyungIn Mikail Choi
user_description: Univ. student of Kyungpook National Univ. Majoring Computer Science and Enigneering. Using this git page for documenting my personal study.
disqus_username: Mikail Choi

# Social Media
# Remove the item if you don't need it
github_username: mikail0205
facebook_username: facebook_mikail0205
instagram_username: instagram_mikail0205
linkedin_username: linkedin_mikail0205

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
